config/routes.rb
Criart::Application.routes.draw do
  resources :catalogs, :only => [:index, :show]

  resources :range_filters, :only => [:index, :show]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :orders, :only => [:index, :show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :line_items, :only => [:index, :show]

  resources :carts, :only => [:index, :show]

  get "store/index"

  resources :properties, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  
  match '/products/popular', :controller => 'products', :action => 'popular'
  
  resources :products, :only => [:index, :show, :popular]

  root :to => "home#index", :as => 'root'
  
  match '/atelier', :controller => 'application', :action => 'atelier'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  scope :bycategory, lambda { |categories| {:include => :properties, :conditions => {:properties => {:id => categories.dup.split(",")}}}}
  
  scope :featured, lambda {where(:feature => true)}
  
  validates :name,:price, :presence => true
  has_many :line_items, :dependent => :destroy
  belongs_to :category
  has_and_belongs_to_many :properties
  
  has_many :product_catalogs
  has_many :catalogs, :through => :product_catalogs

  #before_destroy :ensure_not_referenced_by_any_line_item

##330x230
  has_attached_file :photo,
    :styles => {
      :thumb  => "90x90",
      :medium => "210x150",
      :large => "330x230"
    },
    :storage => :s3,
    :bucket => 'criart',
    :path => ":attachment/:id/:style.:extension",
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
    },
    :default_url => '/unknown.png'

    #attr_accessor :photo_file_name
    #attr_accessor :photo_content_type
    #attr_accessor :photo_file_size
    #attr_accessor :photo_updated_at

  private

  #vai assegurar que quando se apaga um producto que não existe uma linha de encomenda com esse.
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Producto presente numa encomenda.')
      return false
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index, :popular]

  # GET /products
  # GET /products.json
  def index
  #  if params[:category_id].nil?
   #  @products = Product.all
   # else
  #    @products = Product.where(:category_id => params[:category_id])
   # end
    filterProds(params,nil)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end
  
  # GET /products
  # GET /products.json
  def popular 
    @feature = true
    filterProds(params)
    render  'products/index' 
  end
  
  
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @cart = current_cart
    @properties = @product.properties
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @cart = current_cart
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @cart = current_cart
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @cart = current_cart

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    params[:product][:property_ids] ||= []
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
def byProp(products, category, property)
  prod = products
  if @feature
    products = products.featured
  end
  
  if category.blank?
    if @catalog.nil?
      products
    else
      @catalog.products.scoped.find(:all, :conditions => ["products_properties.property_id = ?", property.id], :joins => {:properties =>{}})
    end
  else
      products.where(:category_id => category.id)
  end  
end
end

app/views/products/____index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Reference</th>
    <th>Description</th>
    <th>Price</th>
    <th>Image url</th>
    <th>Thumb url</th>
    <th>Visits</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.reference %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= product.image_url %></td>
    <td><%= product.thumb_url %></td>
    <td><%= product.visits %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Reference:</b>
  <%= @product.reference %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Thumb url:</b>
  <%= @product.thumb_url %>
</p>

<p>
  <b>Photo:</b>
    <%=  @product.photo.url(:medium) %>
    <%= image_tag @product.photo.url(:medium) %>
</p>

<p>
  <b>Visits:</b>
  <%= @product.visits %>
</p>

<p>
    <b>Propriedades</b>
    <% @product.properties.all.each do |property|%>
    <p><%= property.name %></p>
    <% end %>
</p>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reference %><br />
    <%= f.text_area :reference %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :thumb_url %><br />
    <%= f.text_field :thumb_url %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :visits %><br />
    <%= f.number_field :visits %>
  </div>
  <div class="field">
    <label for="product[category_id]">Categoria</label><br />
    <%= collection_select(:product, :category_id, Category.all, :id, :name,{},{:class=>"banana"}) %>
  </div>
  <div class="field">
    <% Property.all.each do |property| %>
    <div>
        <%= check_box_tag "product[property_ids][]", property.id, @product.properties.include?(property) %>
        <%= property.name %>
    <div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% session[:back] = request.fullpath %>
<div id="notice" class="alert-message"><a class="close" href="#">×</a><p><%=notice%><p></div>
<h1>Jóias</h1>
<div class="row">
<div class="span4">
	<div class="filters">
		<h3>Filtros</h3>
		<%= render :partial => "shared/filters" %>
	</div>
</div>

<div class="span12">
	<div class="row">
		<%= render :partial => "shared/products" %>
	</div>
	<div class="row">
		<span class="span3">&nbsp;</span>
		<span class="span9"><%= paginate @products, :outer_window => 1%></span>
	</div>
</div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id="notice" class="alert-message"><a class="close" href="#">×</a><p><%=notice%><p></div>
<div class="container">
    <div class="row mtop60 mbottom30">
		<div class="span1">&nbsp;</div>
		<div class="span6">
			<div id="cloud-wrap">
			<%= link_to image_tag(@product.photo.url(:large), :id => "image"), @product.photo.url, :class => "cloud-zoom", :rel => "adjustX: 10, adjustY:-4, zoomWidth:550, zoomHeight:400,tint:'#fff',tintOpacity:0.6 ,lensOpacity:1"%>
			</div>
			Propriedades<% @properties.each do |p|%>
			<span class="label notice"><%= p.name %></span>
			<%end%>
			<span id="messageZoom" class="label success">Click para Zoom</span>
		</div>	
		<div class="span9">
			<p class="mbottom20">
			  <span id="title"><%= @product.name %></span>
			</p>
			<% if !@product.description.blank? %>
			<p class="mbottom20 mright60">
				<b>Descrição</b><br/>
				<span class="description"><%= @product.description%></span>
			</p>
			<%end%>
				<%= facebook_like :url => url_for(:only_path => false), :class => "complete" %>
				<%= button_to 'Comprar', line_items_path(:product_id => @product), :class => "btn success", :form_class=>"fright", :remote => true %>
				<p class="priceD">
					<strong>
				  		<%= number_to_currency(@product.price)%>
					</strong>
				</p>
		</div>
	</div>
</div>
<% set_meta_tags :title =>  @product.name,
                 :description => @product.description %>