config/routes.rb
Criart::Application.routes.draw do
  resources :catalogs, :only => [:index, :show]

  resources :range_filters, :only => [:index, :show]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :orders, :only => [:index, :show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :line_items, :only => [:index, :show]

  resources :carts, :only => [:index, :show]

  get "store/index"

  resources :properties, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  
  match '/products/popular', :controller => 'products', :action => 'popular'
  
  resources :products, :only => [:index, :show, :popular]

  root :to => "home#index", :as => 'root'
  
  match '/atelier', :controller => 'application', :action => 'atelier'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
	<%= display_meta_tags :site => 'Criart Concept', :description => "Criart Concept, fazemos Jóias à sua medida!" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>
  <body>
<div>
    <div class="container mainContainer">
		<div class="span16 session">
			 <%if !@cart.nil? %>
	              <% if user_signed_in? %>
	                <a href="" id="idUser"><%= current_user.email %></a>
	                <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
	                <%= link_to carts_path do%>
	                    Carrinho <span id="totalElems"><%=@cart.total_quantity%></span>
	                <% end %>
	                <% else %>
	                <%= link_to "Entrar", new_user_session_path %>
	                <%= link_to carts_path do%>
	                    Carrinho <span id="totalElems"><%=@cart.total_quantity%></span>
	                <% end %>
	              <% end %>
	            <%end%>
		</div>
	    <div class="topbar fix <%="criart" unless request.path != "/"%>">
	      <!--div class="fill"-->
	        <div class="container">
	            <h3>
	                <%= link_to image_tag("/assets/logo.png"), root_path, :width => "179px", :height => "40px", :alt => "Criart Concept", :class => "logo"%></h3>
	          <ul class="nav pills">
	            <% Category.find(:all, :order => 'name', :limit => 9).each do |category| %>
	                <li><%= link_to category.name , category_path(category), :class => "catmenu" %></li>
	            <% end %>
	          </ul>
	        </div>
	          <% if request.path == "/" %>
	            <div class="container">
	                <div class="row mtop20 mbottom40">
	                    <div class="span6 first">
	                        <div class="media-grid">
	                            <% Product.find(:all, :order => 'updated_at desc', :limit => 6).each do |product|%>
	                                <div style="float:left;"><%= link_to image_tag(product.photo.url(:thumb), :class => "thumbnail"), product_path(product)%></div>
	                            <%end%>
	                        </div>
	                    </div>
	                    <div class="span8 text-centered mtop20">
	                        <h1>Criart Concept</h1>
	                        <h3 class="home">Fazemos Jóias à sua medida!</h3>
							<%= facebook_like :url => root_url, :class => "begin"%>
	                    </div>
	                </div>
	            </div>
	        <% end %>
	        </div>
      <% if request.path == "/" %>
        <div class="row mbottom40 mtop20">
                <div class="span4 text-centered">
                    <!--<div><img src="https://d1uycljvtt30eq.cloudfront.net/20111114-1/images/home/projects.png" title="Projects" alt="Projects" width="154px" height="90px"></div>-->
                    <div><%= link_to products_path do%>
		                    <img src="/assets/icon-jewel.png" title="Jóias" alt="Jóias">
		                <% end %>
					</div>
                    <h2>Jóias</h2>
                    <h4 class="home">Conheça as nossas jóias</h4>
                </div>
                <div class="span4 text-centered">
                    <!--<div><img src="https://d1uycljvtt30eq.cloudfront.net/20111114-1/images/home/skills.png" title="Skills" alt="Skills" width="154px" height="90px"></div>-->
                    <div><%= link_to catalogs_path do%>
							<img src="/assets/icon-collection.png" title="Colecções" alt="Colecções">
						 <% end %>
					</div>
                    <h2>Coleções</h2>
                    <h4 class="home">Várias coleções para ver</h4>
                </div>
                <div class="span4 text-centered">
                    <!--<div><img src="https://d1uycljvtt30eq.cloudfront.net/20111114-1/images/home/devscore.png" title="DevScore" alt="DevScore" width="154px" height="90px"></div>-->
                    <div><%= link_to "products/popular" do%>
							<img src="/assets/icon-popular.png" title="Populares" alt="Populares">
						<% end %>
					</div>
                    <h2>Populares</h2>
                    <h4 class="home">O que os nossos clientes mais gostam.</h4>
                </div>
                <div class="span4 text-centered">
                    <!--<div><img src="https://d1uycljvtt30eq.cloudfront.net/20111114-1/images/home/achievements.png" title="Achievements" alt="Achievements" width="154px" height="90px"></div>-->
					<%= link_to atelier_path do%>
                		<div><img src="/assets/icon-atelier.png" title="Atelier" alt="Atelier"></div>
					<% end %>
                    <h2>Atelier</h2>
                    <h4 class="home">O nosso atelier</h4>
                </div>
            </div>
        <% end %>
    <div class="main <%= "initial" unless request.path != "/" %>">
		<%if notice%>
			<div id="notice" class="alert-message"><p><%=notice%><p></div>
		<%end%>
		
        <%= yield %>
    </div>

      <footer>
		<%= link_to image_tag("/assets/logo.png", :width => "133px", :height => "28px", :alt => "Criart Concept" ), root_path%>
		<p>&copy; Criart Concept 2012</p>
      </footer>
    </div> <!-- /container -->
<div>

  </body>
</html>